jobs:
  synth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install CDK8s CLI
        run: npm install -g cdk8s-cli

      - name: Run CDK8s Synth
        run: cdk8s synth

      - name: Copy files to rushi directory
        run: |
          mkdir -p rushi
          cp dist/*.yaml rushi/

      - name: Commit and push synthesized YAMLs to rushi/
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add rushi/*.yaml
          git commit -m "chore: copy synthesized YAMLs to rushi/" || echo "No changes to commit"
          git push origin main
