name: CDK8s Synth

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  synth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install CDK8s CLI
        run: npm install -g cdk8s-cli

      - name: Run CDK8s Synth
        run: cdk8s synth

      - name: Commit and push synthesized YAMLs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/*.yaml
          git commit -m "chore: update synthesized Kubernetes manifests" || echo "No changes to commit"
          git push origin main
